spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://121.42.242.95:3306/myfbs?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: fbs-sellergoods-provid  #1、指定当前应用服务的名称，注意服务名不能重复
  registry:
    protocol: zookeeper  #指定注册中心
    address: 121.42.242.95:2181,94.191.54.168:2181,47.103.63.1:2181 #指定注册中心的地址
  #3、指定通讯规则
  protocol:
    name: dubbo #指定消费者和服务提供者的通讯协议是dubbo。即：消费者通过zk访问服务时的协议是dubbo
    port: 20001
server:
  port: 6001
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

